name: food_recipes
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  splash_screen_view: ^3.0.0
  provider: ^6.0.3
  get: ^4.6.5
  flutter_svg: ^1.0.3
  flutter_rating_bar: ^4.0.1
  google_maps_flutter: ^2.2.0
  firebase_auth: ^3.8.0
  firebase_core: ^1.22.0
  cloud_firestore: ^3.4.7
  modal_progress_hud: ^0.1.3
  google_sign_in: ^5.4.1
  flutter_facebook_auth: ^4.4.1
  http: ^0.13.5
  pay: ^1.0.11
  flutter_paystack:
    git:
      url: https://github.com/definitelyme/flutter_paystack.git
      ref: a4a33c3dd0a12f46d655a2e63d11e9f20ba82d01

  geocoding: ^2.0.5
  flutter_google_places: ^0.3.0
  flutter_typeahead: ^4.1.1
  location: ^4.4.0
  location_geocoder: ^1.0.5
  firebase_storage: ^10.3.9
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - images/


  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Inter-Regular.ttf


